import { loadStripe } from '@stripe/stripe-js';

// Initialize Stripe
export const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);

// Your actual subscription plans
export const PLANS = {
  FREE: {
    name: 'Free',
    price: 0,
    features: ['5 quiz attempts per day', 'Basic progress tracking', 'Limited topics'],
    stripePriceId: null
  },
  PRO: {
    name: 'Pro',
    price: 99,
    features: ['Unlimited quiz attempts', 'All 15,000+ questions', 'Advanced analytics', 'All specialties'],
    stripePriceId: 'price_1RsTPUISGmrVXRzqWizONXS7' // Your actual Pro price ID
  },
  PREMIUM: {
    name: 'Premium', 
    price: 99.00,
    features: ['Everything in Pro', 'Access to community question bank', 'Custom smart personal study notes and quizzes generated by highly trained model'],
    stripePriceId: 'prod_So5aXh0MGmE0Hb' // Your actual Premium price ID
  }
};

// Create checkout session
export async function createCheckoutSession(priceId, userId) {
  const response = await fetch('/api/create-checkout-session', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      priceId,
      userId,
    }),
  });

  return await response.json();
}
